### PR TITLE
Fix/nav group layout

### LINKED ISSUE #1163: [BUG] Nav buttons position too low
**Describe the bug**
When a page contains a workshop stepper, the "auto-fill" functionality used in the navigation buttons places them too low. Because of this, even a on screen with little content one needs to scroll to reach the navigation buttons.

This is still the case when there is no workshop stepper, but less so.

**App version**
v0.13.0

**To Reproduce**
Launch the template [debug_stepper_nav_group](https://docs.google.com/spreadsheets/d/18-w6tExfgnSs_majQdZkxkq0jMzqJsJFhOsrmhPfm8g/edit#gid=2032321486) and observe that the navigation buttons in step 1 don't fit on the screen.
Launch the template [debug_stepper_step_1](https://docs.google.com/spreadsheets/d/18-w6tExfgnSs_majQdZkxkq0jMzqJsJFhOsrmhPfm8g/edit#gid=1423621932) and observe that the navigation buttons do fit on the screen, but still there's a little scroll.

**Screenshots and videos**
image
image

### PR DESCRIPTION
**Pull request by chrismclarke**
PR Checklist

- [x] - Latest `master` branch merged
- [x] - PR title descriptive (can be used in release notes)

## Description

Nav groups have fixed 100% height values which can stretch to fit too much space when specific components have margins and/or padding applied. This pr replaces fixed height layouts with flex layout, set to expand to fill available space.

It also removes various pieces of outdated code and tidies what is left.

## Git Issues

Closes #1163

## Screenshots/Videos

image

### CODE REVIEW

File: src/app/shared/components/template/components/layout/nav_group.ts [hunk 1]
```diff
@@ -8,65 +8,55 @@ import { TemplateFieldService } from "../../services/template-field.service";
...
+  template: `
     <div class="nav-progress">
       <div
         *ngFor="let templateName of templateNames; index as i"
         class="nav-progress-part"
-        [ngClass]="{ seen: i <= sectionIndex }"
+        [attr.data-seen]="i <= sectionIndex ? true : null"
         (click)="goToSection(i)"
       ></div>
     </div>
```
Comment (chrismclarke) [inline src/app/shared/components/template/components/layout/nav_group.ts:19]: 4 levels of component nesting reduced to 2 to make layouts more manageable

File: src/app/shared/components/template/components/layout/nav_group.ts [hunk 2]
```diff
@@ -8,65 +8,55 @@ import { TemplateFieldService } from "../../services/template-field.service";
...
+    </div>
+  `,
   styles: [
     `
       :host {
         flex: 1;
         display: flex;
         flex-direction: column;
       }
-
```
Comment (chrismclarke) [inline src/app/shared/components/template/components/layout/nav_group.ts:41]: various style fixes to remove redundant code, fix layout issues and tidying

File: src/app/shared/components/template/components/layout/nav_group.ts [hunk 3]
```diff
@@ -8,65 +8,55 @@ import { TemplateFieldService } from "../../services/template-field.service";
...
       .nav-progress {
         display: flex;
         flex-direction: row;
         justify-content: space-evenly;
-        padding: var(--small-padding) 0;
-      }
-
-      .nav-section :nth-child(1) {
-        height: 100%;
```
Comment (chrismclarke) [inline src/app/shared/components/template/components/layout/nav_group.ts:69]: removed 100% height and replaced with flex

**Review by EsmeeIDEMS — APPROVED** [review]
Functional test passed. While testing I discovered an additional issue #1172, but this was not caused by this PR.

**Review by volloholic — APPROVED** [review]
